name: transcendence

services:
  backend:
    platform: "linux/amd64"
    depends_on:
      postgres:
        condition: service_healthy
    container_name: backend
    build: backend/srcs/backend
    volumes:
      - ./backend/srcs/backend/conf:/transcendence/backend
      - static-volume:/transcendence/backend/staticfiles
      - ./backend/avatars:/transcendence/backend/mediafiles
    restart: on-failure
    env_file:
      - .env
    environment:
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      INTRA42_CLIENT_ID: ${INTRA42_CLIENT_ID}
      INTRA42_CLIENT_SECRET: ${INTRA42_CLIENT_SECRET}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    networks:
      - transcendence
      - elk
    # ports:
    #   - "8080:8000"
    
  postgres:
    container_name: postgres
    image: postgres:17.2
    shm_size: 128mb
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backend/srcs/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./backend/srcs/postgres/init.sql:/docker-entrypoint-initdb.d/init.template.sql.ignore
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    networks:
      - transcendence
      - elk

  nginx:
    depends_on:
      - backend
    container_name: nginx
    build: backend/srcs/nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/frontend
      - static-volume:/etc/nginx/html/static/
      - ./backend/avatars:/etc/nginx/html/media
      - ./backend/srcs/nginx/conf:/etc/nginx/conf.d
      - nginx-log-volume:/var/log/postgres
    environment:
      IP_HOST: ${IP_HOST}
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    networks:
      - transcendence
      - elk

  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - ./backend/srcs/elk/setup_entrypoint.sh:/usr/local/bin/setup_entrypoint.sh:ro
    user: "0"
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      KIBANA_PASSWORD: ${KIBANA_PASSWORD}
      server.ssl.enabled: true
    entrypoint: ["/usr/local/bin/setup_entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120
    networks:
      - elk

  es01:
    depends_on:
      setup:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
      - ./backend/srcs/elk/esbackup:/usr/share/elasticsearch/backup/my_backup
    ports:
      # TODO: only access on localhost
      - 127.0.0.1:9200:9200
    environment:
      - node.name=es01
      - cluster.name=${CLUSTER_NAME}
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/es01/es01.key
      - xpack.security.http.ssl.certificate=certs/es01/es01.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/es01/es01.key
      - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=${LICENSE}
      - xpack.ml.use_auto_machine_memory_percent=true
      - path.repo=/usr/share/elasticsearch/backup
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    logging:
      options:
        tag: "{{.Name}}"
    networks:
      - elk



  kibana:
    depends_on:
      es01:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
      - ./backend/srcs/elk/kibana/kibana_entrypoint.sh:/usr/local/bin/kibana_entrypoint.sh:ro
    ports:
      - ${KIBANA_PORT}:5601
      # IF PRODUCTION
      # - 127.0.0.1:5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=https://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - ENCRYPTED_SAVED_OBJECTS_KEY=${KIBANA_ENCRYPTION_KEY}
      - REPORTING_KEY=${KIBANA_REPORTING_KEY}
      - SECURITY_KEY=${KIBANA_SECURITY_KEY}
    entrypoint: ["/usr/local/bin/kibana_entrypoint.sh"]
    mem_limit: ${KB_MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I --cacert /usr/share/kibana/config/certs/kibana/kibana.crt https://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    logging:
      options:
        tag: "{{.Name}}"
    networks:
      - elk
  
  logstash01:
    depends_on:
      es01:
        condition: service_healthy
      kibana:
        condition: service_healthy
    image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
    labels:
      co.elastic.logs/module: logstash
    user: root
    volumes:
      - certs:/usr/share/logstash/certs
      - logstashdata01:/usr/share/logstash/data
      - "./backend/srcs/elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "./backend/srcs/elk/logstash/logstash.sh:/requirements/elk/logstash/logstash.sh:ro"
      - ./backend/srcs/elk/logstash/logstash_entrypoint.sh:/usr/local/bin/docker-entrypoint:ro
      - ./backend/srcs/elk/kibana/objects:/usr/share/kibana/config/dashboards/
    environment:
      - xpack.monitoring.enabled=false
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=https://es01:9200
    logging:
      options:
        tag: "{{.Name}}"
    networks:
      - elk
    command: ["/bin/bash", "-c", "/requirements/elk/logstash/logstash.sh && logstash -f /usr/share/logstash/pipeline/logstash.conf"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600/_node/stats || exit 1"]

      
volumes:
  static-volume:
  django-log-volume:
  postgres-log-volume:
  nginx-log-volume:

  certs:
    driver: local
  esdata01:
    driver: local
  kibanadata:
    driver: local
  logstashdata01:
    driver: local

networks:
  transcendence:
    driver: bridge
  elk:
    driver: bridge